# Generated by Django 5.1.7 on 2025-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Images'),
        ),
    ]
